Repository saya6/e2e-tests-grupo10, pull requests merged in 2022-05, with the labels that each got.

#5 [HOTFIX] ajustado archivo .gitignore
  .gitignore
Labels: bug

#10 Update README.md
  README.md
Labels: documentation

#14 [FEATURE] Agregados los tests de cypress para el modulo de tags
  Cypress/cypress/integration/tags_tests.js
Labels: enhancement

#16 Update README.md
  README.md
Labels: documentation

#26 Feature/mejora post carlos
  Test-ghost-v4.0.0/Cypress/cypress.json
  Test-ghost-v4.0.0/Cypress/cypress/fixtures/configuration.json
  Test-ghost-v4.0.0/Cypress/cypress/integration/escenario_uno.spec.js
  Test-ghost-v4.0.0/Kraken/features/post_1_crear_post_primer_escenario.feature
  Test-ghost-v4.0.0/Kraken/features/post_2_crear_post_sin_datos_segundo_escenario.feature
  Test-ghost-v4.0.0/Kraken/features/post_3_eliminar_post_publicado_tercer_escenario.feature
  Test-ghost-v4.0.0/Kraken/features/post_4_eliminar_post_no_publicado_cuarto_escenario.feature
  Test-ghost-v4.0.0/Kraken/features/post_5_ver_preview_post_publicado_quinto_escenario.feature
  Test-ghost-v4.0.0/Kraken/features/web/step_definitions/step_login.js
  Test-ghost-v4.0.0/Kraken/features/web/step_definitions/step_posts.js
  Test-ghost-v4.0.0/Kraken/images/crear_post_con_exito/.deleteme
  Test-ghost-v4.0.0/Kraken/images/crear_post_sin_datos/.deleteme
  Test-ghost-v4.0.0/Kraken/images/eliminar_post_no_publicado/.deleteme
  Test-ghost-v4.0.0/Kraken/images/eliminar_post_publicado/.deleteme
  Test-ghost-v4.0.0/Kraken/images/ver_previo_de_post/.deleteme
  Test-ghost-v4.0.0/Kraken/properties.json
  Test-ghost-v4.45.0-min/Cypress/cypress.json
  Test-ghost-v4.45.0-min/Cypress/cypress/integration/escenario_uno.spec.js
  Test-ghost-v4.45.0-min/Kraken/features/post_1_crear_post_primer_escenario.feature
  Test-ghost-v4.45.0-min/Kraken/features/post_2_crear_post_sin_datos_segundo_escenario.feature
  Test-ghost-v4.45.0-min/Kraken/features/post_3_eliminar_post_publicado_tercer_escenario.feature
  Test-ghost-v4.45.0-min/Kraken/features/post_4_eliminar_post_no_publicado_cuarto_escenario.feature
  Test-ghost-v4.45.0-min/Kraken/features/post_5_ver_preview_post_publicado_quinto_escenario.feature
  Test-ghost-v4.45.0-min/Kraken/features/web/step_definitions/step_login.js
  Test-ghost-v4.45.0-min/Kraken/features/web/step_definitions/step_posts.js
  Test-ghost-v4.45.0-min/Kraken/images/crear_post_con_exito/.deleteme
  Test-ghost-v4.45.0-min/Kraken/images/crear_post_sin_datos/.deleteme
  Test-ghost-v4.45.0-min/Kraken/images/eliminar_post_no_publicado/.deleteme
  Test-ghost-v4.45.0-min/Kraken/images/eliminar_post_publicado/.deleteme
  Test-ghost-v4.45.0-min/Kraken/images/ver_previo_de_post/.deleteme
  Test-ghost-v4.45.0/Cypress/cypress.json
  Test-ghost-v4.45.0/Cypress/cypress/integration/escenario_uno.spec.js
  Test-ghost-v4.45.0/Kraken/features/post_1_crear_post_primer_escenario.feature
  Test-ghost-v4.45.0/Kraken/features/post_2_crear_post_sin_datos_segundo_escenario.feature
  Test-ghost-v4.45.0/Kraken/features/post_3_eliminar_post_publicado_tercer_escenario.feature
  Test-ghost-v4.45.0/Kraken/features/post_4_eliminar_post_no_publicado_cuarto_escenario.feature
  Test-ghost-v4.45.0/Kraken/features/post_5_ver_preview_post_publicado_quinto_escenario.feature
  Test-ghost-v4.45.0/Kraken/features/web/step_definitions/step_login.js
  Test-ghost-v4.45.0/Kraken/features/web/step_definitions/step_posts.js
  Test-ghost-v4.45.0/Kraken/images/crear_post_con_exito/.deleteme
  Test-ghost-v4.45.0/Kraken/images/crear_post_sin_datos/.deleteme
  Test-ghost-v4.45.0/Kraken/images/eliminar_post_no_publicado/.deleteme
  Test-ghost-v4.45.0/Kraken/images/eliminar_post_publicado/.deleteme
  Test-ghost-v4.45.0/Kraken/images/ver_previo_de_post/.deleteme
Labels: enhancement

#27 [FEATURE] actualizacion del Makefile
  Makefile
Labels: enhancement

#28 W6 Cypress and Kraken imagenes en sub folderes
  Test-ghost-v4.45.0/.DS_Store
  Test-ghost-v4.45.0/Cypress/.DS_Store
  Test-ghost-v4.45.0/Cypress/cypress/.DS_Store
  Test-ghost-v4.45.0/Cypress/cypress/integration/member_create.spec.js
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/.DS_Store
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/Testing user login + member creation options -- Add myself as Member (failed).png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/Testing user login + member creation options -- Create New Member (failed).png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/Testing user login + member creation options -- Create New Member with Excess Charaters (failed).png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step1-1-login_page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step1-2-login_info_complete.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step1-3-dashboard.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step1-4-member-page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step2-1-login_page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step2-2-login_info_complete.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step2-3-dashboard.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step2-4-member-page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step2-5-new-member-page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step2-6-new-member-page-complete.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step2-7-error.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step2-7-new-member-stored.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step3-1-login_page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step3-2-login_info_complete.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step3-3-dashboard.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step3-4-member-page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step3-5-new-member-page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step3-6-new-member-excess-character-error.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step3-7-new-member-excess-character-fixed.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step3-8-new-member-stored.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step4-1-login_page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step4-2-login_info_complete.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step4-3-dashboard.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step4-4-member-page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step4-5-old-member-view.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step4-6-old-member-edit-complete.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step4-7-old-member-changes-stored.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step5-1-login_page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step5-2-login_info_complete.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step5-3-dashboard.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step5-4-member-page.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step5-5-delete-button.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step5-6-delete-modal.png
  Test-ghost-v4.45.0/Cypress/cypress/screenshots/member_create.spec.js/step5-7-delete-confirm.png
  Test-ghost-v4.45.0/Cypress/images/.DS_Store
  Test-ghost-v4.45.0/Kraken/.kraken/.device_directory
  Test-ghost-v4.45.0/Kraken/.kraken/.devices_ready_to_finish
  Test-ghost-v4.45.0/Kraken/.kraken/.devices_ready_to_start
  Test-ghost-v4.45.0/Kraken/features/member_0_createOwner.feature
  Test-ghost-v4.45.0/Kraken/features/member_1_create.feature
  Test-ghost-v4.45.0/Kraken/features/member_2_createDuplicate.feature
  Test-ghost-v4.45.0/Kraken/features/member_3_deleteCancel.feature
  Test-ghost-v4.45.0/Kraken/features/member_4_deleteDelete.feature
  Test-ghost-v4.45.0/Kraken/features/web/step_definitions/step_members.js
Labels: enhancement

#31 [FEATURE] Agregado target de make para ejecutar pruebas de regresion …
  Makefile
  README.md
Labels: documentation, enhancement

#32 [FEATURE] update de la configuracion del script de reportes
  Report/config.json
Labels: enhancement

#37 Feature/pruebas generacion datos
  .gitignore
  Pruebas-generacion-datos/Cypress/cypress.json
  Pruebas-generacion-datos/Cypress/cypress/fixtures/configuration.json
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-a-priori/MOCK_DATA_POST.json
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-a-priori/escenario_datos_a_priori.spec.js
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-aletorios/escenario_datos_aleatorios.spec.js
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-pseudoaleorios/escenario_datos_pseudoaleorios.spec.js
  Pruebas-generacion-datos/Cypress/cypress/plugins/index.js
  Pruebas-generacion-datos/Cypress/cypress/support/commands.js
  Pruebas-generacion-datos/Cypress/cypress/support/index.js
  Pruebas-generacion-datos/Cypress/package-lock.json
  Pruebas-generacion-datos/Cypress/package.json
Labels: enhancement

#38 [FEATURE] agregados tests para el modulo de tags
  Makefile
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-a-priori/MOCK_DATA_TAGS.json
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-a-priori/escenario_datos_a_priori_tags_tests.js
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-aletorios/escenario_tags_aleatorios_tests.js
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-pseudoaleorios/escenario_tags_datos_pseudoaleatorios.js
Labels: enhancement

#41 [HOTFIX] delete tag screenshots & update createTag function
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-a-priori/escenario_datos_a_priori_tags_tests.js
  Pruebas-generacion-datos/Cypress/cypress/integration/Datos-pseudoaleorios/escenario_tags_datos_pseudoaleatorios.js
Labels: bug

#44 Se agrega script de ripper y monkeys
  Monkeys/README.md
  Monkeys/cypress.json
  Monkeys/cypress/integration/monkey/monkey.js
  Monkeys/cypress/integration/monkey/smart-monkey.js
  Monkeys/cypress/plugins/index.js
  Monkeys/cypress/support/commands.js
  Monkeys/cypress/support/index.js
  Monkeys/monkey-config.json
  Monkeys/package-lock.json
  Monkeys/package.json
  Monkeys/smart-monkey-config.json
  Ripper/LICENSE
  Ripper/README.md
  Ripper/config.json
  Ripper/index.html
  Ripper/index.js
  Ripper/main.css
  Ripper/package-lock.json
  Ripper/package.json
Labels: enhancement
